### ISSUE TITLE
SyntaxError: when installing

### ISSUE THREAD

**Issue by hacklhouse** [Fast-64/fast64#212]
I get this error when doing the install for the fast64 plugin
i just did a fresh install of blender3.4.1 and new download of the plugin

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\robin\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\fast64-main\__init__.py", line 4, in <module>
    from .fast64_internal.operators import AddWaterBox
  File "C:\Users\robin\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\fast64-main\fast64_internal\__init__.py", line 1, in <module>
    from .f3d_material_converter import *
  File "C:\Users\robin\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\fast64-main\fast64_internal\f3d_material_converter.py", line 5, in <module>
    from .f3d.f3d_material import *
  File "C:\Users\robin\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\fast64-main\fast64_internal\f3d\__init__.py", line 1, in <module>
    from .f3d_parser import *
  File "C:\Users\robin\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\fast64-main\fast64_internal\f3d\f3d_parser.py", line 4, in <module>
    from .f3d_gbi import *
  File "C:\Users\robin\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\fast64-main\fast64_internal\f3d\f3d_gbi.py", line 5, in <module>
    from ..utility import *
  File "C:\Users\robin\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\fast64-main\fast64_internal\utility.py", line 1453
    match context.scene.gameEditorMode:
          ^
SyntaxError: invalid syntax

**Comment by Dragorn421** [comment]
Hi, sorry for a very late reply

This error is due to an old version of Python (too old for fast64, at least)

Python is bundled with Blender, recent Blender versions (3.3.0+ or something) have recent enough Python

So no idea why you had this on Blender 3.4.1, if you still have this issue feel free to reach out
