### ISSUE TITLE
Error on exporting insertable binary.

### ISSUE THREAD

**Issue by Bloxifilms** [Fast-64/fast64#263]
Traceback (most recent call last):
  File "C:\Users\teste\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\fast64\fast64_internal\sm64\sm64_geolayout_writer.py", line 3084, in execute
    exportGeolayoutArmatureInsertableBinary(
  File "C:\Users\teste\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\fast64\fast64_internal\sm64\sm64_geolayout_writer.py", line 805, in exportGeolayoutArmatureInsertableBinary
    saveGeolayoutInsertableBinary(geolayoutGraph, fModel, filepath, f3dType)
NameError: name 'f3dType' is not defined

**Comment by sauraen** [comment]
Fixed in #264 and #265
