### ISSUE TITLE
Blender 3 issues with enabling plugin

### ISSUE THREAD

**Issue by lunathir** [Fast-64/fast64#60]
For some reason, Blender 3.0 always throws the following dialog when I try to enable Fast64.

![image](https://user-images.githubusercontent.com/18320914/146713842-19fdb690-a556-4b82-971d-d834e83a2ea9.png)

The following appears in the console as well:

```
Python: Traceback (most recent call last):
  File "C:\Users\cratt\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\fast64-main\fast64_internal\f3d\f3d_material.py", line 1025, in draw
    elif not(material.use_nodes and material.is_f3d):
AttributeError: 'Material' object has no attribute 'is_f3d'

location: <unknown location>:-1
Exception in module register(): C:\Users\cratt\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\fast64-main\__init__.py
Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.0\scripts\modules\addon_utils.py", line 387, in enable
    mod.register()
  File "C:\Users\cratt\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\fast64-main\__init__.py", line 324, in register
    mat_register()
  File "C:\Users\cratt\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\fast64-main\fast64_internal\f3d\f3d_material.py", line 3179, in mat_register
    return os.path.join(presetPath, filename) + ".py"
ValueError: register_class(...): already registered as a subclass 'F3DNodeA'
```

**Comment by Dragorn421** [comment]
Afaict you updated fast64? Does an error still occur after restarting blender.

**Comment by lunathir** [comment]
That was with the latest commit, but restarting Blender seemed to completely fix it and let it work again.
