### ISSUE TITLE
Fast64 Issue when Exporting GeoLayout in Binary Mode

### ISSUE THREAD

**Issue by Retro-Hax** [Fast-64/fast64#99]
Hello so i have an issue when exporting the LowPolySkinnedMario.blend to a Binary Rom the weird thing is that it gives an error even tho exporting the armature work without any issue idk if this a part of my end or a bug in the tool :(

```Traceback (most recent call last):
  File "/home/daria/.config/blender/3.0/scripts/addons/fast64-main/fast64_internal/sm64/sm64_geolayout_writer.py", line 2239, in execute
    addrRange, segPointer = exportGeolayoutObjectBinary(
  File "/home/daria/.config/blender/3.0/scripts/addons/fast64-main/fast64_internal/sm64/sm64_geolayout_writer.py", line 595, in exportGeolayoutObjectBinary
    return saveGeolayoutBinary(romfile, geolayoutGraph, fModel, exportRange,
  File "/home/daria/.config/blender/3.0/scripts/addons/fast64-main/fast64_internal/sm64/sm64_geolayout_writer.py", line 612, in saveGeolayoutBinary
    geolayoutGraph.save_binary(romfile, levelData)
  File "/home/daria/.config/blender/3.0/scripts/addons/fast64-main/fast64_internal/sm64/sm64_geolayout_classes.py", line 130, in save_binary
    geolayout.save_binary(romfile, segmentData)
  File "/home/daria/.config/blender/3.0/scripts/addons/fast64-main/fast64_internal/sm64/sm64_geolayout_classes.py", line 191, in save_binary
    romfile.write(self.to_binary(segmentData))
  File "/home/daria/.config/blender/3.0/scripts/addons/fast64-main/fast64_internal/sm64/sm64_geolayout_classes.py", line 185, in to_binary
    data += node.to_binary(segmentData)
  File "/home/daria/.config/blender/3.0/scripts/addons/fast64-main/fast64_internal/sm64/sm64_geolayout_classes.py", line 310, in to_binary
    data.extend(child.to_binary(segmentData))
  File "/home/daria/.config/blender/3.0/scripts/addons/fast64-main/fast64_internal/sm64/sm64_geolayout_classes.py", line 300, in to_binary
    data = self.node.to_binary(segmentData)
  File "/home/daria/.config/blender/3.0/scripts/addons/fast64-main/fast64_internal/sm64/sm64_geolayout_classes.py", line 762, in to_binary
    command.extend(encodeSegmentedAddr(start_address, segmentData))
  File "/home/daria/.config/blender/3.0/scripts/addons/fast64-main/fast64_internal/utility.py", line 1043, in encodeSegmentedAddr
    segment = getSegment(address, segmentData)
  File "/home/daria/.config/blender/3.0/scripts/addons/fast64-main/fast64_internal/utility.py", line 1054, in getSegment
    raise PluginError("Address " + hex(address) + \
TypeError: 'str' object cannot be interpreted as an integer```

**Comment by Dragorn421** [comment]
Binary mode is vaguely unsupported, like a legacy feature, not really maintained

It'll probably never be fixed, it's more likely to be removed
